// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dex_fund.proto

package org.vite.dex.mm.model.proto;

public final class DexOrderMiningRequest {
  private DexOrderMiningRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VxSettleActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VxSettleAction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes Address = 1;</code>
     */
    com.google.protobuf.ByteString getAddress();

    /**
     * <code>optional bytes Amount = 2;</code>
     */
    com.google.protobuf.ByteString getAmount();
  }
  /**
   * Protobuf type {@code VxSettleAction}
   */
  public  static final class VxSettleAction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VxSettleAction)
      VxSettleActionOrBuilder {
    // Use VxSettleAction.newBuilder() to construct.
    private VxSettleAction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VxSettleAction() {
      address_ = com.google.protobuf.ByteString.EMPTY;
      amount_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VxSettleAction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              address_ = input.readBytes();
              break;
            }
            case 18: {

              amount_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DexOrderMiningRequest.internal_static_VxSettleAction_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DexOrderMiningRequest.internal_static_VxSettleAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DexOrderMiningRequest.VxSettleAction.class, DexOrderMiningRequest.VxSettleAction.Builder.class);
    }

    public static final int ADDRESS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString address_;
    /**
     * <code>optional bytes Address = 1;</code>
     */
    public com.google.protobuf.ByteString getAddress() {
      return address_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString amount_;
    /**
     * <code>optional bytes Amount = 2;</code>
     */
    public com.google.protobuf.ByteString getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!address_.isEmpty()) {
        output.writeBytes(1, address_);
      }
      if (!amount_.isEmpty()) {
        output.writeBytes(2, amount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!address_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, address_);
      }
      if (!amount_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, amount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static DexOrderMiningRequest.VxSettleAction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleAction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DexOrderMiningRequest.VxSettleAction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DexOrderMiningRequest.VxSettleAction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DexOrderMiningRequest.VxSettleAction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VxSettleAction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VxSettleAction)
        DexOrderMiningRequest.VxSettleActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DexOrderMiningRequest.internal_static_VxSettleAction_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DexOrderMiningRequest.internal_static_VxSettleAction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DexOrderMiningRequest.VxSettleAction.class, DexOrderMiningRequest.VxSettleAction.Builder.class);
      }

      // Construct using org.vite.data.dex.bean.proto.DexOrderMiningRequest.VxSettleAction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        address_ = com.google.protobuf.ByteString.EMPTY;

        amount_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DexOrderMiningRequest.internal_static_VxSettleAction_descriptor;
      }

      public DexOrderMiningRequest.VxSettleAction getDefaultInstanceForType() {
        return DexOrderMiningRequest.VxSettleAction.getDefaultInstance();
      }

      public DexOrderMiningRequest.VxSettleAction build() {
        DexOrderMiningRequest.VxSettleAction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DexOrderMiningRequest.VxSettleAction buildPartial() {
        DexOrderMiningRequest.VxSettleAction result = new DexOrderMiningRequest.VxSettleAction(this);
        result.address_ = address_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DexOrderMiningRequest.VxSettleAction) {
          return mergeFrom((DexOrderMiningRequest.VxSettleAction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DexOrderMiningRequest.VxSettleAction other) {
        if (other == DexOrderMiningRequest.VxSettleAction.getDefaultInstance()) return this;
        if (other.getAddress() != com.google.protobuf.ByteString.EMPTY) {
          setAddress(other.getAddress());
        }
        if (other.getAmount() != com.google.protobuf.ByteString.EMPTY) {
          setAmount(other.getAmount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DexOrderMiningRequest.VxSettleAction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DexOrderMiningRequest.VxSettleAction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString address_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Address = 1;</code>
       */
      public com.google.protobuf.ByteString getAddress() {
        return address_;
      }
      /**
       * <code>optional bytes Address = 1;</code>
       */
      public Builder setAddress(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Address = 1;</code>
       */
      public Builder clearAddress() {

        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString amount_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes Amount = 2;</code>
       */
      public com.google.protobuf.ByteString getAmount() {
        return amount_;
      }
      /**
       * <code>optional bytes Amount = 2;</code>
       */
      public Builder setAmount(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes Amount = 2;</code>
       */
      public Builder clearAmount() {

        amount_ = getDefaultInstance().getAmount();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VxSettleAction)
    }

    // @@protoc_insertion_point(class_scope:VxSettleAction)
    private static final DexOrderMiningRequest.VxSettleAction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DexOrderMiningRequest.VxSettleAction();
    }

    public static DexOrderMiningRequest.VxSettleAction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VxSettleAction>
        PARSER = new com.google.protobuf.AbstractParser<VxSettleAction>() {
      public VxSettleAction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new VxSettleAction(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<VxSettleAction> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VxSettleAction> getParserForType() {
      return PARSER;
    }

    public DexOrderMiningRequest.VxSettleAction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VxSettleActionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VxSettleActions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 Period = 1;</code>
     */
    long getPeriod();

    /**
     * <code>optional int32 Page = 2;</code>
     */
    int getPage();

    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    java.util.List<VxSettleAction>
        getActionsList();
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    DexOrderMiningRequest.VxSettleAction getActions(int index);
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    int getActionsCount();
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    java.util.List<? extends VxSettleActionOrBuilder>
        getActionsOrBuilderList();
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    DexOrderMiningRequest.VxSettleActionOrBuilder getActionsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code VxSettleActions}
   */
  public  static final class VxSettleActions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VxSettleActions)
      VxSettleActionsOrBuilder {
    // Use VxSettleActions.newBuilder() to construct.
    private VxSettleActions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VxSettleActions() {
      period_ = 0L;
      page_ = 0;
      actions_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VxSettleActions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              period_ = input.readUInt64();
              break;
            }
            case 16: {

              page_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                actions_ = new java.util.ArrayList<VxSettleAction>();
                mutable_bitField0_ |= 0x00000004;
              }
              actions_.add(input.readMessage(DexOrderMiningRequest.VxSettleAction.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DexOrderMiningRequest.internal_static_VxSettleActions_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DexOrderMiningRequest.internal_static_VxSettleActions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DexOrderMiningRequest.VxSettleActions.class, DexOrderMiningRequest.VxSettleActions.Builder.class);
    }

    private int bitField0_;
    public static final int PERIOD_FIELD_NUMBER = 1;
    private long period_;
    /**
     * <code>optional uint64 Period = 1;</code>
     */
    public long getPeriod() {
      return period_;
    }

    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>optional int32 Page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    public static final int ACTIONS_FIELD_NUMBER = 3;
    private java.util.List<VxSettleAction> actions_;
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    public java.util.List<VxSettleAction> getActionsList() {
      return actions_;
    }
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    public java.util.List<? extends VxSettleActionOrBuilder>
        getActionsOrBuilderList() {
      return actions_;
    }
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    public int getActionsCount() {
      return actions_.size();
    }
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    public DexOrderMiningRequest.VxSettleAction getActions(int index) {
      return actions_.get(index);
    }
    /**
     * <code>repeated .VxSettleAction actions = 3;</code>
     */
    public DexOrderMiningRequest.VxSettleActionOrBuilder getActionsOrBuilder(
        int index) {
      return actions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (period_ != 0L) {
        output.writeUInt64(1, period_);
      }
      if (page_ != 0) {
        output.writeInt32(2, page_);
      }
      for (int i = 0; i < actions_.size(); i++) {
        output.writeMessage(3, actions_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (period_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, period_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      for (int i = 0; i < actions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, actions_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static DexOrderMiningRequest.VxSettleActions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleActions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DexOrderMiningRequest.VxSettleActions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DexOrderMiningRequest.VxSettleActions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DexOrderMiningRequest.VxSettleActions prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VxSettleActions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VxSettleActions)
        DexOrderMiningRequest.VxSettleActionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DexOrderMiningRequest.internal_static_VxSettleActions_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DexOrderMiningRequest.internal_static_VxSettleActions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DexOrderMiningRequest.VxSettleActions.class, DexOrderMiningRequest.VxSettleActions.Builder.class);
      }

      // Construct using org.vite.data.dex.bean.proto.DexOrderMiningRequest.VxSettleActions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getActionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        period_ = 0L;

        page_ = 0;

        if (actionsBuilder_ == null) {
          actions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          actionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DexOrderMiningRequest.internal_static_VxSettleActions_descriptor;
      }

      public DexOrderMiningRequest.VxSettleActions getDefaultInstanceForType() {
        return DexOrderMiningRequest.VxSettleActions.getDefaultInstance();
      }

      public DexOrderMiningRequest.VxSettleActions build() {
        DexOrderMiningRequest.VxSettleActions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DexOrderMiningRequest.VxSettleActions buildPartial() {
        DexOrderMiningRequest.VxSettleActions result = new DexOrderMiningRequest.VxSettleActions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.period_ = period_;
        result.page_ = page_;
        if (actionsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            actions_ = java.util.Collections.unmodifiableList(actions_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.actions_ = actions_;
        } else {
          result.actions_ = actionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DexOrderMiningRequest.VxSettleActions) {
          return mergeFrom((DexOrderMiningRequest.VxSettleActions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DexOrderMiningRequest.VxSettleActions other) {
        if (other == DexOrderMiningRequest.VxSettleActions.getDefaultInstance()) return this;
        if (other.getPeriod() != 0L) {
          setPeriod(other.getPeriod());
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        if (actionsBuilder_ == null) {
          if (!other.actions_.isEmpty()) {
            if (actions_.isEmpty()) {
              actions_ = other.actions_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureActionsIsMutable();
              actions_.addAll(other.actions_);
            }
            onChanged();
          }
        } else {
          if (!other.actions_.isEmpty()) {
            if (actionsBuilder_.isEmpty()) {
              actionsBuilder_.dispose();
              actionsBuilder_ = null;
              actions_ = other.actions_;
              bitField0_ = (bitField0_ & ~0x00000004);
              actionsBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getActionsFieldBuilder() : null;
            } else {
              actionsBuilder_.addAllMessages(other.actions_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DexOrderMiningRequest.VxSettleActions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DexOrderMiningRequest.VxSettleActions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long period_ ;
      /**
       * <code>optional uint64 Period = 1;</code>
       */
      public long getPeriod() {
        return period_;
      }
      /**
       * <code>optional uint64 Period = 1;</code>
       */
      public Builder setPeriod(long value) {

        period_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 Period = 1;</code>
       */
      public Builder clearPeriod() {

        period_ = 0L;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>optional int32 Page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>optional int32 Page = 2;</code>
       */
      public Builder setPage(int value) {

        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 Page = 2;</code>
       */
      public Builder clearPage() {

        page_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<VxSettleAction> actions_ =
        java.util.Collections.emptyList();
      private void ensureActionsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          actions_ = new java.util.ArrayList<VxSettleAction>(actions_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          VxSettleAction, VxSettleAction.Builder, VxSettleActionOrBuilder> actionsBuilder_;

      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public java.util.List<VxSettleAction> getActionsList() {
        if (actionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actions_);
        } else {
          return actionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public int getActionsCount() {
        if (actionsBuilder_ == null) {
          return actions_.size();
        } else {
          return actionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public DexOrderMiningRequest.VxSettleAction getActions(int index) {
        if (actionsBuilder_ == null) {
          return actions_.get(index);
        } else {
          return actionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder setActions(
          int index, DexOrderMiningRequest.VxSettleAction value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.set(index, value);
          onChanged();
        } else {
          actionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder setActions(
          int index, DexOrderMiningRequest.VxSettleAction.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.set(index, builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder addActions(DexOrderMiningRequest.VxSettleAction value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.add(value);
          onChanged();
        } else {
          actionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder addActions(
          int index, DexOrderMiningRequest.VxSettleAction value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.add(index, value);
          onChanged();
        } else {
          actionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder addActions(
          DexOrderMiningRequest.VxSettleAction.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.add(builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder addActions(
          int index, DexOrderMiningRequest.VxSettleAction.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.add(index, builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder addAllActions(
          Iterable<? extends VxSettleAction> values) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actions_);
          onChanged();
        } else {
          actionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder clearActions() {
        if (actionsBuilder_ == null) {
          actions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          actionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public Builder removeActions(int index) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.remove(index);
          onChanged();
        } else {
          actionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public DexOrderMiningRequest.VxSettleAction.Builder getActionsBuilder(
          int index) {
        return getActionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public DexOrderMiningRequest.VxSettleActionOrBuilder getActionsOrBuilder(
          int index) {
        if (actionsBuilder_ == null) {
          return actions_.get(index);  } else {
          return actionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public java.util.List<? extends VxSettleActionOrBuilder>
           getActionsOrBuilderList() {
        if (actionsBuilder_ != null) {
          return actionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actions_);
        }
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public DexOrderMiningRequest.VxSettleAction.Builder addActionsBuilder() {
        return getActionsFieldBuilder().addBuilder(
            DexOrderMiningRequest.VxSettleAction.getDefaultInstance());
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public DexOrderMiningRequest.VxSettleAction.Builder addActionsBuilder(
          int index) {
        return getActionsFieldBuilder().addBuilder(
            index, DexOrderMiningRequest.VxSettleAction.getDefaultInstance());
      }
      /**
       * <code>repeated .VxSettleAction actions = 3;</code>
       */
      public java.util.List<VxSettleAction.Builder>
           getActionsBuilderList() {
        return getActionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          VxSettleAction, VxSettleAction.Builder, VxSettleActionOrBuilder>
          getActionsFieldBuilder() {
        if (actionsBuilder_ == null) {
          actionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              VxSettleAction, VxSettleAction.Builder, VxSettleActionOrBuilder>(
                  actions_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          actions_ = null;
        }
        return actionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VxSettleActions)
    }

    // @@protoc_insertion_point(class_scope:VxSettleActions)
    private static final DexOrderMiningRequest.VxSettleActions DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DexOrderMiningRequest.VxSettleActions();
    }

    public static DexOrderMiningRequest.VxSettleActions getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VxSettleActions>
        PARSER = new com.google.protobuf.AbstractParser<VxSettleActions>() {
      public VxSettleActions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new VxSettleActions(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<VxSettleActions> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VxSettleActions> getParserForType() {
      return PARSER;
    }

    public DexOrderMiningRequest.VxSettleActions getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VxSettleAction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VxSettleAction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VxSettleActions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VxSettleActions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016dex_fund.proto\"1\n\016VxSettleAction\022\017\n\007Ad" +
      "dress\030\001 \001(\014\022\016\n\006Amount\030\002 \001(\014\"Q\n\017VxSettleA" +
      "ctions\022\016\n\006Period\030\001 \001(\004\022\014\n\004Page\030\002 \001(\005\022 \n\007" +
      "actions\030\003 \003(\0132\017.VxSettleActionB5\n\034org.vi" +
      "te.data.dex.bean.protoB\025DexOrderMiningRe" +
      "questb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VxSettleAction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VxSettleAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VxSettleAction_descriptor,
        new String[] { "Address", "Amount", });
    internal_static_VxSettleActions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VxSettleActions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VxSettleActions_descriptor,
        new String[] { "Period", "Page", "Actions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
